print("hello Python", 'Hello py thon programing')
print(50)
print("hello"+"Python")
print("hello"+' ' + "Python")
print()
print(5*10/2)
print("HI python")
name=input("enter your name>")
print("hi!"+ name)
